#!/usr/bin/env python3
"""Generate the public-data migration lineage and history inventories."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REMOVED = ["AAPL", "MSFT", "SPY", "TSLA", "BTC-USD"]


def git(*args: str, text: bool = True):
    return subprocess.check_output(["git", *args], cwd=ROOT, text=text)


def sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def baseline_bytes(commit: str, path: str) -> bytes:
    return git("show", f"{commit}:{path}", text=False)


def write_csv(path: Path, fieldnames: list[str], rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baseline", default="d806943b5bb6d433e4a56e042fd16acdf5ee726d")
    parser.add_argument("--output", type=Path, default=ROOT / "audit/data_release")
    args = parser.parse_args()
    output = args.output.resolve()
    baseline_files = set(git("ls-tree", "-r", "--name-only", args.baseline).splitlines())
    current_tracked = set(git("ls-files").splitlines())
    metadata = json.loads((ROOT / "data/synthetic/metadata.json").read_text())
    rows: list[dict] = []

    columns = ["source_path", "artifact_type", "provider_or_source", "acquisition_method", "ticker",
               "date_range", "price_adjustment_status", "corporate_action_fields", "sha256",
               "tracking_status", "boundary_classification", "release_canonical_status", "manifest_references",
               "reports_or_figures", "validator_dependencies", "redistribution_status", "required_action"]

    baseline_manifests = sorted(path for path in baseline_files if path.startswith("manifests/") and path.endswith(".json") and "/schema/" not in path)
    for ticker in REMOVED:
        path = f"data/{ticker}.csv"
        data = baseline_bytes(args.baseline, path)
        lines = data.decode().splitlines()
        references = []
        for manifest in baseline_manifests:
            if path in baseline_bytes(args.baseline, manifest).decode(errors="replace"):
                references.append(manifest)
        rows.append({
            "source_path": path, "artifact_type": "market_data_input", "provider_or_source": "Yahoo Finance via yfinance",
            "acquisition_method": "historical optional acquisition; exact acquisition metadata incomplete", "ticker": ticker,
            "date_range": f"{lines[1].split(',')[0]}:{lines[-1].split(',')[0]}", "price_adjustment_status": "legacy six-column OHLCV; raw/adjusted provenance incomplete",
            "corporate_action_fields": "none", "sha256": sha256(data), "tracking_status": "removed_from_current_tree;present_in_history",
            "boundary_classification": "historical_third_party", "release_canonical_status": "forbidden",
            "manifest_references": ";".join(references), "reports_or_figures": "baseline results/ descendants",
            "validator_dependencies": "former reproducibility input hash verification", "redistribution_status": "unverified",
            "required_action": "completed: removed from current tree and public canonical boundary",
        })

    for path in sorted(value for value in baseline_files if value.startswith("results/")):
        data = baseline_bytes(args.baseline, path)
        suffix = Path(path).suffix.lower()
        rows.append({
            "source_path": path, "artifact_type": "historical_derived_figure" if suffix == ".png" else "historical_derived_result",
            "provider_or_source": "engine output derived from historical Yahoo-origin inputs", "acquisition_method": "generated by prior engine revision",
            "ticker": "mixed_or_encoded_in_artifact", "date_range": "artifact_specific", "price_adjustment_status": "inherited_from_historical_experiment",
            "corporate_action_fields": "artifact_specific", "sha256": sha256(data), "tracking_status": "removed_from_current_tree;present_in_history",
            "boundary_classification": "historical_empirical_derivative", "release_canonical_status": "not_release_canonical",
            "manifest_references": "legacy package inventory where applicable", "reports_or_figures": path,
            "validator_dependencies": "former regression/result validators", "redistribution_status": "not_asserted",
            "required_action": "completed: removed from tracked release tree; summaries retained only as qualified documentation",
        })

    for entry in metadata["assets"]:
        path = ROOT / "data/synthetic" / entry["filename"]
        rows.append({
            "source_path": str(path.relative_to(ROOT)), "artifact_type": "synthetic_market_data_input",
            "provider_or_source": metadata["generator_id"], "acquisition_method": "offline deterministic fixed-point generation",
            "ticker": entry["asset"], "date_range": f"{entry['date_range']['start']}:{entry['date_range']['end']}",
            "price_adjustment_status": "raw OHLC plus deterministic total-return adjusted close",
            "corporate_action_fields": "AdjustedClose;Dividends;StockSplits", "sha256": entry["sha256"],
            "tracking_status": "tracked", "boundary_classification": "synthetic", "release_canonical_status": "public_canonical",
            "manifest_references": "all public synthetic package manifests", "reports_or_figures": "generated public synthetic package outputs",
            "validator_dependencies": "synthetic validator; public boundary validator; reproducibility validator",
            "redistribution_status": "project_owned_apache_2_0", "required_action": "retain and verify byte-for-byte regeneration",
        })

    for path in sorted((ROOT / "results").rglob("*")) if (ROOT / "results").exists() else []:
        if not path.is_file():
            continue
        relative = str(path.relative_to(ROOT))
        classification = "synthetic_local_output" if relative.startswith("results/public_synthetic/") else "historical_or_local_output"
        rows.append({
            "source_path": relative, "artifact_type": "ignored_generated_output", "provider_or_source": "local engine/report tooling",
            "acquisition_method": "generated locally", "ticker": "artifact_specific", "date_range": "artifact_specific",
            "price_adjustment_status": "experiment_specific", "corporate_action_fields": "artifact_specific",
            "sha256": sha256(path.read_bytes()), "tracking_status": "ignored_local_only", "boundary_classification": classification,
            "release_canonical_status": "not_bundled; expected identity retained in public manifests when synthetic",
            "manifest_references": "public manifests when under results/public_synthetic", "reports_or_figures": relative,
            "validator_dependencies": "result/package validators as applicable", "redistribution_status": "not_a_release_asset",
            "required_action": "keep ignored; never package local historical outputs",
        })

    rows.append({
        "source_path": "data/local/", "artifact_type": "user_supplied_input_boundary", "provider_or_source": "user_declared",
        "acquisition_method": "user supplied or optional local acquisition", "ticker": "user_defined", "date_range": "user_defined",
        "price_adjustment_status": "must be declared by user", "corporate_action_fields": "six- or nine-column supported schema",
        "sha256": "resolved_locally", "tracking_status": "ignored", "boundary_classification": "user_supplied",
        "release_canonical_status": "never_public_canonical", "manifest_references": "local ignored manifest only",
        "reports_or_figures": "local only", "validator_dependencies": "validate_market_data.py; generate_local_data_manifest.py",
        "redistribution_status": "user_responsibility_not_granted_by_project", "required_action": "keep ignored and validate before local execution",
    })
    write_csv(output / "data_lineage_inventory.csv", columns, rows)

    history_rows = []
    history_columns = ["path", "file_sha256", "git_blob_sha", "first_commit", "first_commit_date",
                       "latest_commit_containing_file", "current_migration_tree_contains", "current_branch_contains",
                       "historical_commits_expose_file", "tags_containing", "release_assets_containing", "history_status"]
    for ticker in REMOVED:
        path = f"data/{ticker}.csv"
        data = baseline_bytes(args.baseline, path)
        first = git("log", "--all", "--follow", "--format=%H|%ad", "--date=short", "--", path).splitlines()[-1]
        history_rows.append({
            "path": path, "file_sha256": sha256(data), "git_blob_sha": git("rev-parse", f"{args.baseline}:{path}").strip(),
            "first_commit": first.split("|")[0], "first_commit_date": first.split("|")[1],
            "latest_commit_containing_file": args.baseline, "current_migration_tree_contains": str(path in current_tracked).lower(),
            "current_branch_contains": str(path in current_tracked).lower(), "historical_commits_expose_file": "true",
            "tags_containing": "none_detected", "release_assets_containing": "none_detected",
            "history_status": "removed_from_current_tree_but_reachable_from_historical_commit",
        })
    write_csv(output / "history_occurrences.csv", history_columns, history_rows)
    print(f"Wrote {len(rows)} lineage rows and {len(history_rows)} history rows to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
