#!/usr/bin/env python3
"""Validate deterministic synthetic OHLCV fixtures and their provenance metadata."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import tempfile
from datetime import date, timedelta
from pathlib import Path

from generate_synthetic_market_data import ASSETS, GENERATOR_ID, SCHEMA, generate


class ValidationError(RuntimeError):
    pass


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _number(row: dict[str, str], field: str) -> float:
    try:
        value = float(row[field])
    except (KeyError, ValueError) as error:
        raise ValidationError(f"invalid {field}") from error
    if not math.isfinite(value):
        raise ValidationError(f"non-finite {field}")
    return value


def validate(directory: Path, regenerate_check: bool = False) -> dict:
    metadata_path = directory / "metadata.json"
    if not metadata_path.is_file():
        raise ValidationError("missing metadata.json")
    metadata = json.loads(metadata_path.read_text())
    if metadata.get("classification") != "synthetic" or metadata.get("generator_id") != GENERATOR_ID:
        raise ValidationError("invalid synthetic classification or generator identity")
    if metadata.get("network_required") is not False or metadata.get("schema") != SCHEMA:
        raise ValidationError("invalid offline or schema metadata")

    declared = {entry["asset"]: entry for entry in metadata.get("assets", [])}
    if set(declared) != set(ASSETS):
        raise ValidationError("synthetic asset inventory mismatch")

    for asset, entry in declared.items():
        if entry.get("classification") != "synthetic" or entry.get("filename") != f"{asset}.csv":
            raise ValidationError(f"invalid classification for {asset}")
        path = directory / entry["filename"]
        if not path.is_file() or _sha256(path) != entry.get("sha256"):
            raise ValidationError(f"hash mismatch for {asset}")
        with path.open(newline="") as stream:
            reader = csv.DictReader(stream)
            if reader.fieldnames != SCHEMA:
                raise ValidationError(f"schema mismatch for {asset}")
            rows = list(reader)
        if len(rows) != entry.get("row_count") or not rows:
            raise ValidationError(f"row count mismatch for {asset}")
        dates: list[date] = []
        for row in rows:
            current = date.fromisoformat(row["Date"])
            if dates and current <= dates[-1]:
                raise ValidationError(f"dates not unique and increasing for {asset}")
            dates.append(current)
            open_price, high, low, close = (_number(row, field) for field in ("Open", "High", "Low", "Close"))
            adjusted = _number(row, "AdjustedClose")
            volume = _number(row, "Volume")
            dividend = _number(row, "Dividends")
            split = _number(row, "StockSplits")
            if min(open_price, high, low, close, adjusted) <= 0 or volume < 0 or dividend < 0 or split < 0:
                raise ValidationError(f"invalid value domain for {asset} on {current}")
            if high < max(open_price, close) or low > min(open_price, close) or high < low:
                raise ValidationError(f"invalid OHLC relationship for {asset} on {current}")
            if entry["calendar"] == "synthetic_weekday" and current.weekday() >= 5:
                raise ValidationError(f"weekend row in weekday fixture {asset}")
        if entry.get("date_range") != {"start": rows[0]["Date"], "end": rows[-1]["Date"]}:
            raise ValidationError(f"date range mismatch for {asset}")
        if entry["calendar"] == "synthetic_seven_day":
            missing = {date.fromisoformat(value) for value in entry.get("missing_dates", [])}
            expected = (dates[-1] - dates[0]).days + 1 - len(missing)
            if len(dates) != expected:
                raise ValidationError(f"seven-day calendar mismatch for {asset}")

    if regenerate_check:
        with tempfile.TemporaryDirectory(prefix="synthetic-data-check-") as temp:
            regenerated = Path(temp)
            generate(regenerated)
            expected_names = sorted(path.name for path in directory.iterdir() if path.is_file())
            actual_names = sorted(path.name for path in regenerated.iterdir() if path.is_file())
            if expected_names != actual_names:
                raise ValidationError("regenerated file inventory mismatch")
            for name in expected_names:
                if (directory / name).read_bytes() != (regenerated / name).read_bytes():
                    raise ValidationError(f"regenerated bytes differ for {name}")
    return metadata


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path, nargs="?", default=Path("data/synthetic"))
    parser.add_argument("--regenerate-check", action="store_true")
    args = parser.parse_args()
    try:
        metadata = validate(args.directory, args.regenerate_check)
    except (ValidationError, ValueError, json.JSONDecodeError) as error:
        print(f"Synthetic data validation failed: {error}")
        return 1
    print(f"Synthetic data validation passed: {len(metadata['assets'])} assets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
